In [1]:
import numpy as np

In [49]:
# 0: sunny, 1: cloudy, 2: rainy 
'''
  @param
    firstDay: weather of first data
    n: how many day you want to show
'''
def getProbability(firstDay = 0, nDay=4):
    M = np.array([[0.8, 0.4, 0.2], [0.2, 0.4, 0.6], [0, 0.2, 0.2]]) # transition matrix
    v = np.zeros((3, 1))
    v[firstDay] = 1
    print("\t  Sunny  Cloudy  Rainy\t\n")
    print("Day: {:d}  {:.5f} {:.5f} {:.5f}\n".format(1, v[0][0], v[1][0], v[2][0]))
    for i in range(nDay-1):
        v = np.dot(M, v)
        print("Day: {:d}  {:.5f} {:.5f} {:.5f}\n".format(i+2, v[0][0], v[1][0], v[2][0]))

In [50]:
getProbability(0, 5)

	  Sunny  Cloudy  Rainy	

Day: 1  1.00000 0.00000 0.00000

Day: 2  0.80000 0.20000 0.00000

Day: 3  0.72000 0.24000 0.04000

Day: 4  0.68000 0.26400 0.05600

Day: 5  0.66080 0.27520 0.06400



In [2]:
M = np.array([[0.8, 0.4, 0.2], [0.2, 0.4, 0.6], [0, 0.2, 0.2]]) # transition matrix
w, v = np.linalg.eig(M)

In [52]:
w

array([ 1.        ,  0.48284271, -0.08284271])

In [53]:
v

array([[-0.90913729,  0.81251992,  0.23258782],
       [-0.40406102, -0.47596315, -0.79410449],
       [-0.10101525, -0.33655677,  0.56151667]])

In [54]:
dia = np.diag(w)

In [55]:
dia

array([[ 1.        ,  0.        ,  0.        ],
       [ 0.        ,  0.48284271,  0.        ],
       [ 0.        ,  0.        , -0.08284271]])

In [56]:
dia_n = np.linalg.matrix_power(dia, 100)

In [57]:
dia_n

array([[1.00000000e+000, 0.00000000e+000, 0.00000000e+000],
       [0.00000000e+000, 2.40197288e-032, 0.00000000e+000],
       [0.00000000e+000, 0.00000000e+000, 6.69007571e-109]])

In [60]:
np.dot(np.dot(v,dia_n), np.linalg.inv(v))

array([[0.64285714, 0.64285714, 0.64285714],
       [0.28571429, 0.28571429, 0.28571429],
       [0.07142857, 0.07142857, 0.07142857]])

In [62]:
v*dia_n*np.linalg.inv(v)

array([[ 6.42857143e-001, -0.00000000e+000, -0.00000000e+000],
       [-0.00000000e+000,  7.36529507e-033,  0.00000000e+000],
       [-0.00000000e+000,  0.00000000e+000,  3.78190628e-109]])

In [66]:
# entropy
9./14*np.log2(14/9.)+4./14*np.log2(14/4.)+1./14*np.log2(14)

1.1981174211304033

In [3]:
C = np.array([[0.6, 0.3, 0], [0.4, 0.7, 0], [0, 0, 1]])

In [5]:
np.dot(C, M)

array([[0.54, 0.36, 0.3 ],
       [0.46, 0.44, 0.5 ],
       [0.  , 0.2 , 0.2 ]])

In [6]:
0.6*0.54*0.04*0.8

0.010368000000000002

In [8]:
np.dot(C, np.linalg.matrix_power(M, 2))

array([[0.504, 0.42 , 0.384],
       [0.456, 0.46 , 0.456],
       [0.04 , 0.12 , 0.16 ]])

In [10]:
(0.6*0.54*0.04*0.8)/(0.6*0.54*0.04*0.8+0.3*0.36*0.12*0.2)

0.8